name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: install aws cli and login
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools
        pip3 install -U awscli
    - name: login to ecr
      run: $(aws ecr get-login --no-include-email --region us-east-1)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
